# Generated by Django 2.2.1 on 2019-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='appid',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
