# Generated by Django 2.2.1 on 2019-06-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0002_auto_20190604_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='appid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
